default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: avia_development

test:
  <<: *default
  database: avia_test

production:
  <<: *default
  database: avia_production